# "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms." 
(1..40).inject([1]){|fib,i| i < 2 ? fib << 1 : fib << fib[i-1]+ fib[i-2]}.select{|fe| fe if (fe.even? && fe<4000000)}.inject(0){|sum,i| sum = sum + i}